<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Reports\ResourceReportGenerateMsg.pt-BR.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Reports\ResourceReportGenerateMsg.pt-BR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceReportGenerateMsg.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Reports\ResourceReportGenerateMsg.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceReportGenerateMsg.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Reports\ResourceReportGenerateMsg.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceReportGenerateMsg.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
