<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Petfólio.Comunication\Petfólio.Comunication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="responses\" />
    <Folder Include="Use Case\User\" />
  </ItemGroup>

</Project>
