<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.application\CashFlow.application.csproj" />
    <ProjectReference Include="..\CashFlow.communication\CashFlow.communication.csproj" />
    <ProjectReference Include="..\CashFlow.Exeption\CashFlow.Exeption.csproj" />
    <ProjectReference Include="..\CashFlow.Infraestrutura\CashFlow.Infraestrutura.csproj" />
  </ItemGroup>

</Project>
