<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.communication\CashFlow.communication.csproj" />
    <ProjectReference Include="..\CashFlow.Domain\CashFlow.Domain.csproj" />
    <ProjectReference Include="..\CashFlow.Exeption\CashFlow.Exeption.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UseCases\Expenses\Reports\Pdf\Fonts\Minecrafter.Reg.ttf" />
    <EmbeddedResource Include="UseCases\Expenses\Reports\Pdf\Fonts\Roboto-VariableFont_wdth,wght.ttf" />
    <EmbeddedResource Include="UseCases\Expenses\Reports\Pdf\Fonts\STJEDISE.TTF" />
  </ItemGroup>

</Project>
